language: python
sudo: false
python:
- '3.6'
env:
  - DJANGO="Django>=1.11,<1.12.0"
  - DJANGO="Django>=2.2,<2.3"
install:
  - pip install -q $DJANGO
  - pip install -q -r test_reqs.txt
  - pip install coveralls
script:
  - flake8 quizblock
  - python runtests.py
  - coverage run --source=quizblock runtests.py
after_success:
  - coveralls
